# This workflow will build a Java project with Gradle
name: InterMine build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env: 
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    env:
      TESTMODEL_URL: http://localhost:8080/intermine-demo
      TESTMODEL_PATH: intermine-demo
      TERM: dumb

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Set up python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: '2.7'  
    #- name: Install Solr
    #  run: ./config/travis/init-solr.sh
    - name: test db
      run: createdb -U postgres -c danitest 
    #- name: Run intermine unit tests
     # env:
        #TEST_SUITE: intermine 
      #run: ./config/travis/init.sh && ./config/travis/run.sh
    #- name: Run bio unit tests
     # env:
      #  TEST_SUITE: bio
      #run: ./config/travis/init.sh && ./config/travis/run.sh
